/**
 * src/main.js —— 游戏入口（ES Module 唯一入口）
 *
 * 原单文件 game.js 已按拓扑层拆入同目录 *-*.js（共 5 段，依赖单向、无环）。
 * 本文件只做两件事：
 *   1. 静态 import 全部模块段（编译期即确定求值顺序，被依赖者先求值）
 *   2. 把"原经典脚本会泄漏到 window 的名字"桥接回 window
 *
 * 为什么要桥接：index.html 原本用经典脚本加载 game.js，经典脚本的顶层
 *   `const SND = ...` / `function boot(){}` 会自动成为 window 属性；ES Module 不会。
 *   不补这一步，平台注入脚本 / 外部测试 / 调试命令里的 `SND.xxx` 全部失效。
 *
 * 为什么全局只有这一个入口：模块图必须每个文件唯一 URL，否则同一模块被实例化两遍，
 *   共享状态（state / SND / 缓存）分裂成两份（v3.0 的 ?v= 混用就是这么出的问题）。
 */
import * as NS_src_00_pure_js from './00-pure.js';
import * as NS_src_10_base_js from './10-base.js';
import * as NS_src_20_core_js from './20-core.js';
import * as NS_src_30_systems_js from './30-systems.js';
import * as NS_src_40_app_js from './40-app.js';
import * as NS_src_60_stage_js from './60-stage.js';
/* v6 挂机重构：核心数值层 + 整合层 + DOM 层 */
import * as NS_src_00_num_js from './00-num.js';
import * as NS_src_00_stage_js from './00-stage.js';
import * as NS_src_00_equip_js from './00-equip.js';
import * as NS_src_00_rebirth_js from './00-rebirth.js';
import * as NS_src_05_v6_js from './05-v6.js';
import * as NS_src_06_v6ui_js from './06-v6ui.js';

/* 把模块内声明桥接到 window（只补缺失的，不覆盖已有全局）*/
const BRIDGE = {
  "ARMOR_POOL": function () { return NS_src_00_pure_js["ARMOR_POOL"]; },
  "ARRAY_COST": function () { return NS_src_00_pure_js["ARRAY_COST"]; },
  "ARRAY_MAX_LV": function () { return NS_src_00_pure_js["ARRAY_MAX_LV"]; },
  "ART_PREFIX": function () { return NS_src_00_pure_js["ART_PREFIX"]; },
  "ART_SPECIAL": function () { return NS_src_00_pure_js["ART_SPECIAL"]; },
  "ART_SUFFIX": function () { return NS_src_00_pure_js["ART_SUFFIX"]; },
  "AURA_COLORS": function () { return NS_src_00_pure_js["AURA_COLORS"]; },
  "AURA_FPS": function () { return NS_src_00_pure_js["AURA_FPS"]; },
  "BIGS": function () { return NS_src_00_pure_js["BIGS"]; },
  "BTL": function () { return NS_src_00_pure_js["BTL"]; },
  "BUFF_CAP_MS": function () { return NS_src_00_pure_js["BUFF_CAP_MS"]; },
  "CACHE_VER": function () { return NS_src_00_pure_js["CACHE_VER"]; },
  "CLD_ALPH": function () { return NS_src_00_pure_js["CLD_ALPH"]; },
  "CLD_API": function () { return NS_src_10_base_js["CLD_API"]; },
  "CLD_KEY": function () { return NS_src_00_pure_js["CLD_KEY"]; },
  "CLOUD_PUSH_MIN": function () { return NS_src_00_pure_js["CLOUD_PUSH_MIN"]; },
  "CUR_VER": function () { return NS_src_00_pure_js["CUR_VER"]; },
  "DAN_ZONE": function () { return NS_src_00_pure_js["DAN_ZONE"]; },
  "DEV_KEY": function () { return NS_src_00_pure_js["DEV_KEY"]; },
  "DIMSTAT": function () { return NS_src_00_pure_js["DIMSTAT"]; },
  "DROP_CFG": function () { return NS_src_00_pure_js["DROP_CFG"]; },
  "EQUI_CELLPOS": function () { return NS_src_00_pure_js["EQUI_CELLPOS"]; },
  "EQUI_ICON": function () { return NS_src_00_pure_js["EQUI_ICON"]; },
  "EQUI_SLOTI": function () { return NS_src_00_pure_js["EQUI_SLOTI"]; },
  "EQUI_SLOTN": function () { return NS_src_10_base_js["EQUI_SLOTN"]; },
  "EVENTS": function () { return NS_src_00_pure_js["EVENTS"]; },
  "FX_POOL": function () { return NS_src_00_pure_js["FX_POOL"]; },
  "FX_TXT": function () { return NS_src_00_pure_js["FX_TXT"]; },
  "G1_TPL": function () { return NS_src_00_pure_js["G1_TPL"]; },
  "GAME_VER": function () { return NS_src_00_pure_js["GAME_VER"]; },
  "JRN_CAP": function () { return NS_src_00_pure_js["JRN_CAP"]; },
  "JRN_TAIL": function () { return NS_src_00_pure_js["JRN_TAIL"]; },
  "LIC_QCOL": function () { return NS_src_00_pure_js["LIC_QCOL"]; },
  "MAIL_CAP": function () { return NS_src_00_pure_js["MAIL_CAP"]; },
  "MAIN_STORY": function () { return NS_src_00_pure_js["MAIN_STORY"]; },
  "MATS": function () { return NS_src_00_pure_js["MATS"]; },
  "MIGRATIONS": function () { return NS_src_00_pure_js["MIGRATIONS"]; },
  "MON_ATK_SCALE": function () { return NS_src_00_pure_js["MON_ATK_SCALE"]; },
  "MON_FX_POOL": function () { return NS_src_00_pure_js["MON_FX_POOL"]; },
  "MON_NAMES": function () { return NS_src_00_pure_js["MON_NAMES"]; },
  "MS_ARRAY": function () { return NS_src_00_pure_js["MS_ARRAY"]; },
  "MS_ART": function () { return NS_src_00_pure_js["MS_ART"]; },
  "MS_SPIRIT": function () { return NS_src_00_pure_js["MS_SPIRIT"]; },
  "MYST": function () { return NS_src_00_pure_js["MYST"]; },
  "OFFLINE_CAP": function () { return NS_src_00_pure_js["OFFLINE_CAP"]; },
  "PAGES_NEED": function () { return NS_src_00_pure_js["PAGES_NEED"]; },
  "PEND_POOL": function () { return NS_src_00_pure_js["PEND_POOL"]; },
  "PET": function () { return NS_src_00_pure_js["PET"]; },
  "PET_BONUS": function () { return NS_src_00_pure_js["PET_BONUS"]; },
  "PET_COIN": function () { return NS_src_00_pure_js["PET_COIN"]; },
  "PET_FORGE": function () { return NS_src_00_pure_js["PET_FORGE"]; },
  "PET_STILL": function () { return NS_src_00_pure_js["PET_STILL"]; },
  "PLOT": function () { return NS_src_00_pure_js["PLOT"]; },
  "QUALITY": function () { return NS_src_00_pure_js["QUALITY"]; },
  "REALM_DAYS": function () { return NS_src_00_pure_js["REALM_DAYS"]; },
  "RECIPES": function () { return NS_src_00_pure_js["RECIPES"]; },
  "RK_NAMES": function () { return NS_src_00_pure_js["RK_NAMES"]; },
  "RK_SEGS": function () { return NS_src_00_pure_js["RK_SEGS"]; },
  "SAVE_KEY": function () { return NS_src_00_pure_js["SAVE_KEY"]; },
  "SCROLL_POOL": function () { return NS_src_00_pure_js["SCROLL_POOL"]; },
  "SEARCH_MAX": function () { return NS_src_00_pure_js["SEARCH_MAX"]; },
  "SEARCH_MIN": function () { return NS_src_00_pure_js["SEARCH_MIN"]; },
  "SEG4": function () { return NS_src_00_pure_js["SEG4"]; },
  "SEG_META": function () { return NS_src_00_pure_js["SEG_META"]; },
  "SEG_SCALE": function () { return NS_src_00_pure_js["SEG_SCALE"]; },
  "SKILL_DEFS": function () { return NS_src_00_pure_js["SKILL_DEFS"]; },
  "SKILL_MAX": function () { return NS_src_00_pure_js["SKILL_MAX"]; },
  "SLOT_TYPES": function () { return NS_src_00_pure_js["SLOT_TYPES"]; },
  "SND": function () { return NS_src_10_base_js["SND"]; },
  "SPIRIT_RATE": function () { return NS_src_00_pure_js["SPIRIT_RATE"]; },
  "STORY_BY_KEY": function () { return NS_src_00_pure_js["STORY_BY_KEY"]; },
  "STORY_BY_SID": function () { return NS_src_00_pure_js["STORY_BY_SID"]; },
  "STORY_PAGE": function () { return NS_src_00_pure_js["STORY_PAGE"]; },
  "TOTAL_SEGS": function () { return NS_src_10_base_js["TOTAL_SEGS"]; },
  "TRACE_ACT": function () { return NS_src_00_pure_js["TRACE_ACT"]; },
  "TRAVEL_FIRST_MAX": function () { return NS_src_00_pure_js["TRAVEL_FIRST_MAX"]; },
  "TRAVEL_FIRST_STEP": function () { return NS_src_00_pure_js["TRAVEL_FIRST_STEP"]; },
  "TRAVEL_FIRST_WINDOW": function () { return NS_src_00_pure_js["TRAVEL_FIRST_WINDOW"]; },
  "TRAVEL_LATE_STEP": function () { return NS_src_00_pure_js["TRAVEL_LATE_STEP"]; },
  "TRAVEL_SPAN": function () { return NS_src_00_pure_js["TRAVEL_SPAN"]; },
  "ZONES": function () { return NS_src_00_pure_js["ZONES"]; },
  "_auraAcc": function () { return NS_src_10_base_js["_auraAcc"]; },
  "_auraColor": function () { return NS_src_10_base_js["_auraColor"]; },
  "_auraCtx": function () { return NS_src_10_base_js["_auraCtx"]; },
  "_auraCv": function () { return NS_src_10_base_js["_auraCv"]; },
  "_auraP": function () { return NS_src_10_base_js["_auraP"]; },
  "_auraT": function () { return NS_src_10_base_js["_auraT"]; },
  "_cloudSettleRun": function () { return NS_src_20_core_js["_cloudSettleRun"]; },
  "_dropSaveT": function () { return NS_src_00_pure_js["_dropSaveT"]; },
  "_dsp": function () { return NS_src_00_pure_js["_dsp"]; },
  "_encNext": function () { return NS_src_00_pure_js["_encNext"]; },
  "_eqRecycle": function () { return NS_src_00_pure_js["_eqRecycle"]; },
  "_eqSel": function () { return NS_src_00_pure_js["_eqSel"]; },
  "_equipId": function () { return NS_src_00_pure_js["_equipId"]; },
  "_equipQueue": function () { return NS_src_00_pure_js["_equipQueue"]; },
  "_floatPrev": function () { return NS_src_00_pure_js["_floatPrev"]; },
  "_hbFails": function () { return NS_src_00_pure_js["_hbFails"]; },
  "_hiddenAt": function () { return NS_src_00_pure_js["_hiddenAt"]; },
  "_hudAcc": function () { return NS_src_00_pure_js["_hudAcc"]; },
  "_kicked": function () { return NS_src_00_pure_js["_kicked"]; },
  "_lastPick": function () { return NS_src_00_pure_js["_lastPick"]; },
  "_pred": function () { return NS_src_00_pure_js["_pred"]; },
  "_rate": function () { return NS_src_00_pure_js["_rate"]; },
  "_rkAt": function () { return NS_src_00_pure_js["_rkAt"]; },
  "_settling": function () { return NS_src_00_pure_js["_settling"]; },
  "_skillSaveT": function () { return NS_src_00_pure_js["_skillSaveT"]; },
  "_srvOffset": function () { return NS_src_00_pure_js["_srvOffset"]; },
  "_stayLast": function () { return NS_src_00_pure_js["_stayLast"]; },
  "_storyChap": function () { return NS_src_00_pure_js["_storyChap"]; },
  "_syncAt": function () { return NS_src_00_pure_js["_syncAt"]; },
  "_traceLoc": function () { return NS_src_00_pure_js["_traceLoc"]; },
  "_tracePool": function () { return NS_src_00_pure_js["_tracePool"]; },
  "_traceT": function () { return NS_src_00_pure_js["_traceT"]; },
  "_travelReturned": function () { return NS_src_00_pure_js["_travelReturned"]; },
  "addJournal": function () { return NS_src_20_core_js["addJournal"]; },
  "adopt": function () { return NS_src_10_base_js["adopt"]; },
  "adoptKeep": function () { return NS_src_20_core_js["adoptKeep"]; },
  "adventure": function () { return NS_src_40_app_js["adventure"]; },
  "alHave": function () { return NS_src_10_base_js["alHave"]; },
  "alIco": function () { return NS_src_10_base_js["alIco"]; },
  "alIcoCls": function () { return NS_src_00_pure_js["alIcoCls"]; },
  "alInFurn": function () { return NS_src_10_base_js["alInFurn"]; },
  "alTip": function () { return NS_src_10_base_js["alTip"]; },
  "alTipT": function () { return NS_src_00_pure_js["alTipT"]; },
  "apiRoot": function () { return NS_src_10_base_js["apiRoot"]; },
  "applyDropRates": function () { return NS_src_20_core_js["applyDropRates"]; },
  "applyEquipDrop": function () { return NS_src_40_app_js["applyEquipDrop"]; },
  "arrMult": function () { return NS_src_00_pure_js["arrMult"]; },
  "arrayCostNow": function () { return NS_src_10_base_js["arrayCostNow"]; },
  "artCtx": function () { return NS_src_10_base_js["artCtx"]; },
  "artMult": function () { return NS_src_10_base_js["artMult"]; },
  "artName": function () { return NS_src_10_base_js["artName"]; },
  "artScore": function () { return NS_src_20_core_js["artScore"]; },
  "attrAssign": function () { return NS_src_10_base_js["attrAssign"]; },
  "auraColorNow": function () { return NS_src_30_systems_js["auraColorNow"]; },
  "autoHuntOn": function () { return NS_src_00_pure_js["autoHuntOn"]; },
  "bctx": function () { return NS_src_10_base_js["bctx"]; },
  "bcv": function () { return NS_src_10_base_js["bcv"]; },
  "bigIdx": function () { return NS_src_20_core_js["bigIdx"]; },
  "bigSub": function () { return NS_src_00_pure_js["bigSub"]; },
  "bindBattleHooks": function () { return NS_src_40_app_js["bindBattleHooks"]; },
  "boot": function () { return NS_src_40_app_js["boot"]; },
  "bootCloud": function () { return NS_src_40_app_js["bootCloud"]; },
  "bootGate": function () { return NS_src_40_app_js["bootGate"]; },
  "breaking": function () { return NS_src_00_pure_js["breaking"]; },
  "buffAtCap": function () { return NS_src_10_base_js["buffAtCap"]; },
  "buffHintOf": function () { return NS_src_10_base_js["buffHintOf"]; },
  "buffMult": function () { return NS_src_10_base_js["buffMult"]; },
  "buffSpanMs": function () { return NS_src_10_base_js["buffSpanMs"]; },
  "burstBoom": function () { return NS_src_10_base_js["burstBoom"]; },
  "capDeviceDpr": function () { return NS_src_00_pure_js["capDeviceDpr"]; },
  "cauldron": function () { return NS_src_00_pure_js["cauldron"]; },
  "checkMilestones": function () { return NS_src_30_systems_js["checkMilestones"]; },
  "cld": function () { return NS_src_00_pure_js["cld"]; },
  "cldAdoptCloud": function () { return NS_src_40_app_js["cldAdoptCloud"]; },
  "cldApi": function () { return NS_src_10_base_js["cldApi"]; },
  "cldApiBase": function () { return NS_src_00_pure_js["cldApiBase"]; },
  "cldChip": function () { return NS_src_10_base_js["cldChip"]; },
  "cldFail": function () { return NS_src_20_core_js["cldFail"]; },
  "cldFlash": function () { return NS_src_10_base_js["cldFlash"]; },
  "cldId": function () { return NS_src_10_base_js["cldId"]; },
  "cldPull": function () { return NS_src_40_app_js["cldPull"]; },
  "cldPush": function () { return NS_src_30_systems_js["cldPush"]; },
  "cldUI": function () { return NS_src_10_base_js["cldUI"]; },
  "closeAlchemy": function () { return NS_src_10_base_js["closeAlchemy"]; },
  "closeEquip": function () { return NS_src_10_base_js["closeEquip"]; },
  "closeLic": function () { return NS_src_30_systems_js["closeLic"]; },
  "closeMail": function () { return NS_src_10_base_js["closeMail"]; },
  "closeOffline": function () { return NS_src_10_base_js["closeOffline"]; },
  "closeRank": function () { return NS_src_10_base_js["closeRank"]; },
  "closeRename": function () { return NS_src_10_base_js["closeRename"]; },
  "closeSettings": function () { return NS_src_10_base_js["closeSettings"]; },
  "closeSkills": function () { return NS_src_10_base_js["closeSkills"]; },
  "closeStory": function () { return NS_src_10_base_js["closeStory"]; },
  "closeTravel": function () { return NS_src_10_base_js["closeTravel"]; },
  "cloudBind": function () { return NS_src_40_app_js["cloudBind"]; },
  "cloudCopyId": function () { return NS_src_20_core_js["cloudCopyId"]; },
  "cloudFlush": function () { return NS_src_40_app_js["cloudFlush"]; },
  "cloudInit": function () { return NS_src_40_app_js["cloudInit"]; },
  "cloudNew": function () { return NS_src_10_base_js["cloudNew"]; },
  "cloudPullNow": function () { return NS_src_40_app_js["cloudPullNow"]; },
  "cloudPushNow": function () { return NS_src_30_systems_js["cloudPushNow"]; },
  "cloudSettle": function () { return NS_src_30_systems_js["cloudSettle"]; },
  "cloudSnap": function () { return NS_src_10_base_js["cloudSnap"]; },
  "cloudSoon": function () { return NS_src_10_base_js["cloudSoon"]; },
  "cloudTogglePanel": function () { return NS_src_10_base_js["cloudTogglePanel"]; },
  "cnNum": function () { return NS_src_00_pure_js["cnNum"]; },
  "collectAllMail": function () { return NS_src_40_app_js["collectAllMail"]; },
  "collectMail": function () { return NS_src_40_app_js["collectMail"]; },
  "consumePill": function () { return NS_src_40_app_js["consumePill"]; },
  "craftPill": function () { return NS_src_40_app_js["craftPill"]; },
  "debugEncounter": function () { return NS_src_10_base_js["debugEncounter"]; },
  "deviceId": function () { return NS_src_10_base_js["deviceId"]; },
  "dimRender": function () { return NS_src_10_base_js["dimRender"]; },
  "doBreak": function () { return NS_src_40_app_js["doBreak"]; },
  "doCraft": function () { return NS_src_40_app_js["doCraft"]; },
  "durTxt": function () { return NS_src_00_pure_js["durTxt"]; },
  "ensureScrollFx": function () { return NS_src_10_base_js["ensureScrollFx"]; },
  "enterDim": function () { return NS_src_10_base_js["enterDim"]; },
  "eqMult": function () { return NS_src_00_pure_js["eqMult"]; },
  "equipBonus": function () { return NS_src_10_base_js["equipBonus"]; },
  "esc": function () { return NS_src_00_pure_js["esc"]; },
  "exitDim": function () { return NS_src_10_base_js["exitDim"]; },
  "fallbackCopy": function () { return NS_src_20_core_js["fallbackCopy"]; },
  "fin": function () { return NS_src_00_pure_js["fin"]; },
  "finalStats": function () { return NS_src_00_pure_js["finalStats"]; },
  "fireMilestone": function () { return NS_src_30_systems_js["fireMilestone"]; },
  "fitsRecipe": function () { return NS_src_10_base_js["fitsRecipe"]; },
  "fmt": function () { return NS_src_00_pure_js["fmt"]; },
  "fmtFxTag": function () { return NS_src_10_base_js["fmtFxTag"]; },
  "fxAgg": function () { return NS_src_00_pure_js["fxAgg"]; },
  "fxCount": function () { return NS_src_00_pure_js["fxCount"]; },
  "fxValue": function () { return NS_src_00_pure_js["fxValue"]; },
  "g1Pack": function () { return NS_src_10_base_js["g1Pack"]; },
  "g1Unpack": function () { return NS_src_10_base_js["g1Unpack"]; },
  "g1b64": function () { return NS_src_00_pure_js["g1b64"]; },
  "g1merge": function () { return NS_src_00_pure_js["g1merge"]; },
  "g1prune": function () { return NS_src_00_pure_js["g1prune"]; },
  "g1unb64": function () { return NS_src_00_pure_js["g1unb64"]; },
  "genMonster": function () { return NS_src_10_base_js["genMonster"]; },
  "handleKicked": function () { return NS_src_10_base_js["handleKicked"]; },
  "hbFail": function () { return NS_src_10_base_js["hbFail"]; },
  "hbOk": function () { return NS_src_00_pure_js["hbOk"]; },
  "hiddenUnlocked": function () { return NS_src_10_base_js["hiddenUnlocked"]; },
  "initAura": function () { return NS_src_10_base_js["initAura"]; },
  "initBg": function () { return NS_src_10_base_js["initBg"]; },
  "initBg2D": function () { return NS_src_10_base_js["initBg2D"]; },
  "initFxDiag": function () { return NS_src_00_pure_js["initFxDiag"]; },
  "initFxLayer": function () { return NS_src_10_base_js["initFxLayer"]; },
  "journalHasKey": function () { return NS_src_10_base_js["journalHasKey"]; },
  "keepArtQuiet": function () { return NS_src_20_core_js["keepArtQuiet"]; },
  "lastReadyHint": function () { return NS_src_00_pure_js["lastReadyHint"]; },
  "licBuild": function () { return NS_src_10_base_js["licBuild"]; },
  "licSync": function () { return NS_src_20_core_js["licSync"]; },
  "load": function () { return NS_src_20_core_js["load"]; },
  "loadRank": function () { return NS_src_20_core_js["loadRank"]; },
  "loadRecipe": function () { return NS_src_30_systems_js["loadRecipe"]; },
  "locById": function () { return NS_src_10_base_js["locById"]; },
  "loop": function () { return NS_src_40_app_js["loop"]; },
  "mailClaim": function () { return NS_src_40_app_js["mailClaim"]; },
  "mailDot": function () { return NS_src_10_base_js["mailDot"]; },
  "mailLine": function () { return NS_src_10_base_js["mailLine"]; },
  "mainMoment": function () { return NS_src_30_systems_js["mainMoment"]; },
  "makeArt": function () { return NS_src_30_systems_js["makeArt"]; },
  "manualBreak": function () { return NS_src_40_app_js["manualBreak"]; },
  "matBagHTML": function () { return NS_src_10_base_js["matBagHTML"]; },
  "migrate": function () { return NS_src_10_base_js["migrate"]; },
  "onBattleDrop": function () { return NS_src_40_app_js["onBattleDrop"]; },
  "openAlchemy": function () { return NS_src_30_systems_js["openAlchemy"]; },
  "openEquip": function () { return NS_src_30_systems_js["openEquip"]; },
  "openMail": function () { return NS_src_20_core_js["openMail"]; },
  "openRank": function () { return NS_src_20_core_js["openRank"]; },
  "openRename": function () { return NS_src_10_base_js["openRename"]; },
  "openSettings": function () { return NS_src_20_core_js["openSettings"]; },
  "openSkills": function () { return NS_src_30_systems_js["openSkills"]; },
  "openStory": function () { return NS_src_30_systems_js["openStory"]; },
  "openTravel": function () { return NS_src_30_systems_js["openTravel"]; },
  "pagesOf": function () { return NS_src_10_base_js["pagesOf"]; },
  "parts": function () { return NS_src_00_pure_js["parts"]; },
  "pickArt": function () { return NS_src_30_systems_js["pickArt"]; },
  "pickLoc": function () { return NS_src_30_systems_js["pickLoc"]; },
  "pickNoRepeat": function () { return NS_src_10_base_js["pickNoRepeat"]; },
  "pickQ": function () { return NS_src_30_systems_js["pickQ"]; },
  "pillCabinetHTML": function () { return NS_src_10_base_js["pillCabinetHTML"]; },
  "pillIco": function () { return NS_src_10_base_js["pillIco"]; },
  "presentSettle": function () { return NS_src_40_app_js["presentSettle"]; },
  "pulseChip": function () { return NS_src_00_pure_js["pulseChip"]; },
  "pushBattleStats": function () { return NS_src_10_base_js["pushBattleStats"]; },
  "pushBuff": function () { return NS_src_10_base_js["pushBuff"]; },
  "pushMsg": function () { return NS_src_10_base_js["pushMsg"]; },
  "putMat": function () { return NS_src_30_systems_js["putMat"]; },
  "rateNow": function () { return NS_src_30_systems_js["rateNow"]; },
  "realm": function () { return NS_src_20_core_js["realm"]; },
  "realmMult": function () { return NS_src_30_systems_js["realmMult"]; },
  "realmPlot": function () { return NS_src_40_app_js["realmPlot"]; },
  "recipeCan": function () { return NS_src_10_base_js["recipeCan"]; },
  "recipeCardHTML": function () { return NS_src_10_base_js["recipeCardHTML"]; },
  "refreshGlow": function () { return NS_src_30_systems_js["refreshGlow"]; },
  "refreshOpenPanel": function () { return NS_src_40_app_js["refreshOpenPanel"]; },
  "renderAlch": function () { return NS_src_30_systems_js["renderAlch"]; },
  "renderAutoHunt": function () { return NS_src_10_base_js["renderAutoHunt"]; },
  "renderBag": function () { return NS_src_10_base_js["renderBag"]; },
  "renderCabinet": function () { return NS_src_10_base_js["renderCabinet"]; },
  "renderCraftBtn": function () { return NS_src_20_core_js["renderCraftBtn"]; },
  "renderEquip": function () { return NS_src_30_systems_js["renderEquip"]; },
  "renderFurn": function () { return NS_src_10_base_js["renderFurn"]; },
  "renderMailBox": function () { return NS_src_20_core_js["renderMailBox"]; },
  "renderPName": function () { return NS_src_10_base_js["renderPName"]; },
  "renderPillHints": function () { return NS_src_10_base_js["renderPillHints"]; },
  "renderRecipes": function () { return NS_src_30_systems_js["renderRecipes"]; },
  "renderSettings": function () { return NS_src_10_base_js["renderSettings"]; },
  "renderSkills": function () { return NS_src_20_core_js["renderSkills"]; },
  "renderStory": function () { return NS_src_30_systems_js["renderStory"]; },
  "requestEquipDrop": function () { return NS_src_40_app_js["requestEquipDrop"]; },
  "resetDimKnob": function () { return NS_src_10_base_js["resetDimKnob"]; },
  "rkSegLabel": function () { return NS_src_10_base_js["rkSegLabel"]; },
  "rnOk": function () { return NS_src_00_pure_js["rnOk"]; },
  "rollFx": function () { return NS_src_10_base_js["rollFx"]; },
  "rollMonFx": function () { return NS_src_10_base_js["rollMonFx"]; },
  "save": function () { return NS_src_20_core_js["save"]; },
  "saveRename": function () { return NS_src_20_core_js["saveRename"]; },
  "searchMs": function () { return NS_src_10_base_js["searchMs"]; },
  "seekHide": function () { return NS_src_00_pure_js["seekHide"]; },
  "seg": function () { return NS_src_10_base_js["seg"]; },
  "selRecipe": function () { return NS_src_00_pure_js["selRecipe"]; },
  "setProg": function () { return NS_src_00_pure_js["setProg"]; },
  "setRealmSub": function () { return NS_src_10_base_js["setRealmSub"]; },
  "settleBlocked": function () { return NS_src_10_base_js["settleBlocked"]; },
  "showChapter": function () { return NS_src_20_core_js["showChapter"]; },
  "showTravelMail": function () { return NS_src_20_core_js["showTravelMail"]; },
  "sizeBurst": function () { return NS_src_10_base_js["sizeBurst"]; },
  "skillAddExp": function () { return NS_src_20_core_js["skillAddExp"]; },
  "skillAddExpAll": function () { return NS_src_30_systems_js["skillAddExpAll"]; },
  "skillDef": function () { return NS_src_10_base_js["skillDef"]; },
  "skillExpNeed": function () { return NS_src_00_pure_js["skillExpNeed"]; },
  "skillGet": function () { return NS_src_10_base_js["skillGet"]; },
  "skillLv": function () { return NS_src_10_base_js["skillLv"]; },
  "skillTotalLv": function () { return NS_src_20_core_js["skillTotalLv"]; },
  "skillVal": function () { return NS_src_20_core_js["skillVal"]; },
  "smartEquip": function () { return NS_src_20_core_js["smartEquip"]; },
  "spawnFloat": function () { return NS_src_00_pure_js["spawnFloat"]; },
  "spiritRate": function () { return NS_src_10_base_js["spiritRate"]; },
  "srvNow": function () { return NS_src_10_base_js["srvNow"]; },
  "startGame": function () { return NS_src_40_app_js["startGame"]; },
  "startHeartbeat": function () { return NS_src_40_app_js["startHeartbeat"]; },
  "startTravel": function () { return NS_src_40_app_js["startTravel"]; },
  "state": function () { return NS_src_00_pure_js["state"]; },
  "stayMailCheck": function () { return NS_src_40_app_js["stayMailCheck"]; },
  "storyItemHtml": function () { return NS_src_10_base_js["storyItemHtml"]; },
  "storyLoadMore": function () { return NS_src_20_core_js["storyLoadMore"]; },
  "storyResolve": function () { return NS_src_10_base_js["storyResolve"]; },
  "takeMat": function () { return NS_src_30_systems_js["takeMat"]; },
  "tapArray": function () { return NS_src_40_app_js["tapArray"]; },
  "tickAura": function () { return NS_src_30_systems_js["tickAura"]; },
  "tickBurst": function () { return NS_src_10_base_js["tickBurst"]; },
  "tickDsp": function () { return NS_src_10_base_js["tickDsp"]; },
  "toggleBgm": function () { return NS_src_20_core_js["toggleBgm"]; },
  "toggleSfx": function () { return NS_src_20_core_js["toggleSfx"]; },
  "traceBeat": function () { return NS_src_20_core_js["traceBeat"]; },
  "traceRefresh": function () { return NS_src_10_base_js["traceRefresh"]; },
  "traceTap": function () { return NS_src_30_systems_js["traceTap"]; },
  "travelAvatarHTML": function () { return NS_src_30_systems_js["travelAvatarHTML"]; },
  "travelBtnLbl": function () { return NS_src_10_base_js["travelBtnLbl"]; },
  "travelMailCount": function () { return NS_src_10_base_js["travelMailCount"]; },
  "travelNextMailIn": function () { return NS_src_10_base_js["travelNextMailIn"]; },
  "travelSecForMails": function () { return NS_src_10_base_js["travelSecForMails"]; },
  "travelSent": function () { return NS_src_10_base_js["travelSent"]; },
  "trimJournal": function () { return NS_src_10_base_js["trimJournal"]; },
  "trimJr": function () { return NS_src_10_base_js["trimJr"]; },
  "updateArts": function () { return NS_src_20_core_js["updateArts"]; },
  "updateHUD": function () { return NS_src_30_systems_js["updateHUD"]; },
  "updateRealmUI": function () { return NS_src_20_core_js["updateRealmUI"]; },
  "zoneOfBig": function () { return NS_src_10_base_js["zoneOfBig"]; },
  "zoneOfLoc": function () { return NS_src_10_base_js["zoneOfLoc"]; },
  "段名": function () { return NS_src_10_base_js["段名"]; },
  /* v3.2 统一舞台层 */
  "initStage": function () { return NS_src_60_stage_js["initStage"]; },
  "battleBand": function () { return NS_src_60_stage_js["battleBand"]; },
  "$": function () { return NS_src_00_pure_js["$"]; },

  /* ── v6 挂机重构 ────────────────────────────────────────────────
   * 只有【被 index.html 的 onclick 调用】的名字才需要桥接。
   * 纯数学层（00-num/00-stage/00-equip/00-rebirth）不桥 —— 它们只在模块间
   * 用 import 引用，泄漏到 window 只会让全局名字变脏，没有收益。 */
  "upEquip": function () { return NS_src_06_v6ui_js["upEquip"]; },
  "setStep": function () { return NS_src_06_v6ui_js["setStep"]; },
  "doRebirthUI": function () { return NS_src_06_v6ui_js["doRebirthUI"]; },
  "closeRebirth": function () { return NS_src_06_v6ui_js["closeRebirth"]; },
  "confirmRebirth": function () { return NS_src_06_v6ui_js["confirmRebirth"]; },
  /* 调试入口：window.V6 可查状态与手动结算 */
  "V6": function () {
    return {
      init: NS_src_06_v6ui_js["initV6"],
      tick: NS_src_06_v6ui_js["tick6"],
      render: NS_src_06_v6ui_js["render6"],
      state: NS_src_06_v6ui_js["state6"],
      load: NS_src_06_v6ui_js["loadV6"],
      save: NS_src_06_v6ui_js["saveV6"],
      offline: NS_src_06_v6ui_js["settleOffline6"],
      step: NS_src_06_v6ui_js["getStep"],
      num: NS_src_00_num_js,
      stage: NS_src_00_stage_js,
      equip: NS_src_00_equip_js,
      rebirth: NS_src_00_rebirth_js,
      core: NS_src_05_v6_js,
    };
  },
};
for (const k in BRIDGE) {
  if (Object.prototype.hasOwnProperty.call(window, k)) continue;
  try {
    Object.defineProperty(window, k, { get: BRIDGE[k], configurable: true });
  } catch (e) { /* 某些名字可能已被平台以不可配置方式定义，跳过即可 */ }
}

/* ── 战斗模块（由 index.html 内联脚本抽取，见 tools/extract_battle.js）─────────
 * 用动态 import 而不是顶部静态 import，只为「顺序」：战斗模块求值时立刻 init()，
 * 会读 window.BattleAPI 的挂接方（20-core/40-app 的 bindBattleHooks 虽在轮询，
 * 但先桥接后加载能让首帧就拿到正确属性，少 300ms 的兜底等待）。
 * ⚠️ 这里【不能】带 ?v= query —— 一带就与模块间静态 import 解析出的 URL 不同，
 *    同一文件被实例化两遍，SND/state 分裂（v3.0 的坑）。缓存由 HTTP 层负责。
 */
import('./50-battle.js');

/* ── v6 挂机重构：初始化 ─────────────────────────────────────────────────
 * 放在 50-battle 动态 import 之后。50-battle 的 init() 会读 window.state 建战斗
 * 实体；v6 的初始化只建自己的子状态与 DOM，不依赖战斗实体，故延后一档最安全。
 *
 * 为什么用 setTimeout 0 而不是直接调用：
 *   40-app 的 boot()/startGame() 是异步的（要先过云存档门禁），window.state 在
 *   那之后才可信。这里等一个宏任务，让启动链路先把 state 铺好；initV6 内部对
 *   state 缺失有完整容错（退化成全新 v6 状态），因此即使启动失败也不会白屏。
 */
setTimeout(function () {
  try {
    NS_src_06_v6ui_js.initV6(typeof window !== 'undefined' ? window.state : null);
  } catch (e) {
    console.warn('[v6] 初始化失败:', e);
  }
}, 0);
